#! /bin/sh
#
# Convenience driver script.  If lqt was compiled locally, use that
# version.  Otherwise, fallback to the pre-built self-standing
# executable jar shipped with the distribution.

cd `dirname $0`

if [ -e target/classes/com/basistech/lucene/tools/LuceneQueryTool.class ]; then
    java -Dfile.encoding=UTF-8 -cp `cat classpath.txt`:target/classes com.basistech.lucene.tools.LuceneQueryTool "$@"
else
    java -Dfile.encoding=UTF-8 -jar lqt-*-jar-with-dependencies.jar "$@"
fi
