#! /bin/sh
#
# Convenience driver script.

dir=$(dirname $0)
CP=$dir:$dir/target/classes:$(cat $dir/classpath.txt)

if [ -e $dir/target/classes/com/basistech/lucene/tools/LuceneQueryTool.class ]; then
    java $JVM_ARGS -Dfile.encoding=UTF-8 -cp $CP com.basistech.lucene.tools.LuceneQueryTool "$@"
else
    echo "Please run 'mvn compile' first."
    exit 1
fi
