#! /bin/sh
#
# Convenience driver script.  If lqt was compiled locally, use that
# version.  Otherwise, fallback to the pre-built self-standing
# executable jar shipped with the distribution.

dir=$(dirname $0)
echo $dir
CP=$dir:$dir/target/classes:$(cat $dir/classpath.txt)

if [ -e $dir/target/classes/com/basistech/lucene/tools/LuceneQueryTool.class ]; then
    java -Dfile.encoding=UTF-8 -cp $CP com.basistech.lucene.tools.LuceneQueryTool "$@"
else
    java -Dfile.encoding=UTF-8 -jar $dir/lqt-*-jar-with-dependencies.jar "$@"
fi
